name: Data Engineering Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Python and SQL Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install flake8 sqlfluff

      - name: Lint Python (Syntax Errors)
        run: |
          # 파이썬 오타 및 치명적 에러 검사
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Lint SQL (SparkSQL Dialect)
        run: |
          # 모든 폴더 내 SQL 문법 검사 (데이터브릭스용 SparkSQL 기준)
          sqlfluff lint . --dialect sparksql